### ISSUE TITLE
Settle on a visual style

### ISSUE THREAD

**Issue by ellaklara** [DH2413-AGI/InTheShadows#36]
Sketches, "concept art" etc.
Game visuals

- [ ] Mood (visual concept, colours)
- [ ] Character
- [ ] General assets (shapes, keep it simple)
- [ ] Create tasks for assets (important!)
- [ ] Create tasks for shaders (important!)

Assets can't be too complicated:
https://www.omniaz.io/news/what-do-ar-ready-models-mean-building-3d-models-for-augmented-reality
"As a rule of thumb, keeping the file under 5mb is good."

**Comment by AdamJonsson** [comment]
My suggestion is on having a nature / city hybride where we are placing known objects (e.g Eiffel tower) in a nature settings. Like some kind of futuristic mode where humanity is instinct. 

![f2udkzmjxso01](https://user-images.githubusercontent.com/13873828/134310055-a6ad6c5a-d607-4b71-92f9-b6a6f4b8ff58.jpg)

I think that a nature is easier to model than a city. The background for keeping in the shadows is that the suns radiation is to strong in the future
